name: Deploy Preview to GitHub Pages

on:
  workflow_run:
    workflows: ["Build Preview Deployment"] # nome do workflow que gera o site
    types:
      - completed

permissions:
  actions: read
  deployments: write
  contents: read
  pull-requests: write

jobs:
  deploy-preview:
    if: ${{ github.repository == 'RicardoS2/Site-ibracon' && github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    name: Deploy Preview to GitHub Pages

    steps:
      # 1️⃣ Baixar o build artifact do workflow anterior
      - name: Download build artifact
        uses: actions/download-artifact@v7
        id: preview-build
        with:
          name: preview-build
          path: build
          github-token: ${{ secrets.GITHUB_TOKEN }}
          run-id: ${{ github.event.workflow_run.id }}

      # 2️⃣ Publicar no GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v5
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          publish_branch: gh-pages
          keep_files: false
